services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  usuarios:
    build:
      context: ./microservicios/usuarios
      dockerfile: Dockerfile
    container_name: usuarios
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=usuariosDB
    links:
      - db

  productos:
    build:
      context: ./microservicios/productos
      dockerfile: Dockerfile
    container_name: productos
    ports:
      - "3002:3002"
    environment:
      - DB_NAME=productosDB
    links:
      - db

  ordenes:
     build:
      context: ./microservicios/ordenes
      dockerfile: Dockerfile
    container_name: ordenes
    ports:
      - "3003:3003"
    environment:
      - DB_NAME=ordenesDB
    links:
      - db
      - usuarios
      - productos

  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"
    links:
      - usuarios
      - productos
      - ordenes
